"""add invoice_date

Revision ID: 46b307df2197
Revises: fdae2e16f39a
Create Date: 2026-06-28 03:28:06.828245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46b307df2197'
down_revision: Union[str, Sequence[str], None] = 'fdae2e16f39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('invoice_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'invoice_date')
    # ### end Alembic commands ###
