"""add installments

Revision ID: c26ac59bcc6d
Revises: 29545e8cab1a
Create Date: 2026-06-28 02:42:42.390276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c26ac59bcc6d'
down_revision: Union[str, Sequence[str], None] = '29545e8cab1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('installment', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('total_installments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_installments')
    op.drop_column('transactions', 'installment')
    # ### end Alembic commands ###
