"""add credit_card_id

Revision ID: fdae2e16f39a
Revises: 3916e00b6a2b
Create Date: 2026-06-28 03:19:28.342294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdae2e16f39a'
down_revision: Union[str, Sequence[str], None] = '3916e00b6a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('credit_card_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'credit_card_id')
    # ### end Alembic commands ###
